### PR TITLE
Add file support

### PR DESCRIPTION
**Pull request by tybritten**

### CODE REVIEW

**Comment by Olen** [comment]
Looks good on first sight, however there were a lot of ' -> " changes as well in the first patch, so I might have missed something.

On the other hand, I have more or less completely rewritten the integration in my repo, and added config_flow to set up calendars using the GUI etc.
https://github.com/Olen/ical-sensor-homeassistant

This version also includes a much better handling of events that crosses DST and missing timezone info in events etc. 
I just wanted to test it a bit more before I pushed it back here, and since this repo has been sleeping for a while I did not prioritize it...
Do you think we could be able to merge them?

**Comment by tybritten** [comment]
I just was going through that. Your version is significantly better. Do you think we could merge without breaking existing configs?

**Comment by Olen** [comment]
Probably, but it requires some code to convert the config from yaml to config flow.
I only had 3 calendars, so I did not bother.  Took me just a few seconds to set them up again.

**Comment by tybritten** [comment]
Good point, we can just notate it as a major version breaking change. Want to PR it in?

**Comment by tybritten** [comment]
or do you want to just publish from yours and I can mark this as depreciated

**Comment by Olen** [comment]
It will be a pretty big PR.  I can give it a try and see what github thinks about it.
But won't be able to do that until tomorrow (European time here).

**Pull request closed without merging**
