### PR TITLE
Added HACS compatibility

### PR DESCRIPTION
**Pull request by basschipper**
HACS integration documentation: 
https://custom-components.github.io/hacs/developer/integration/

After merging, please create a release eg. "v0.2.0"

### CODE REVIEW

**Comment by Martinvdm** [comment]
I think you should still release it, cannot find it in HACS yet

**Comment by basschipper** [comment]
Yes, it needs to be added to the data branch of HACS.

But, first a release needs to be published on this repo, eg. "v0.2.0".
Besides that I think that we may need to delete the current "0.1.1" release as well because it does not meet the HACS structure.

@tybritten Can you delete the current version and add a new one?

**Comment by tybritten** [comment]
ok I did that and it works if you add this repo to HACS. I submitted a PR to have it added to the data branch https://github.com/custom-components/hacs/pull/240

**Comment by tybritten** [comment]
ok they merged it so it should be in the HACS store now

**Comment by basschipper** [comment]
Awesome!

**Comment by tybritten** [comment]
thanks for all your help on this one. I didn't even know about HACS before

**Comment by quentinsf** [comment]
Yes, this is great - I installed HACS yesterday and was about to fix this here when the message came through that someone had already done it!  Many thanks!

**Comment by Martinvdm** [comment]
i don't see it in the HACS store. is this is only some time or do they need to accept it somehow? rebooted HA already

**Comment by tybritten** [comment]
You have to refresh data in HACS. It takes a few minutes

**Pull request merged**
